# Generated by Django 4.2.16 on 2024-10-17 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('yom', models.IntegerField(max_length=4)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.body')),
            ],
        ),
    ]
