# Generated by Django 5.1.4 on 2024-12-17 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_id', models.IntegerField(default=0)),
                ('body_name', models.CharField(default='+', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.IntegerField(default=0)),
                ('color_name', models.CharField(default='white', max_length=20)),
                ('color_code', models.CharField(default='FFF', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_id', models.IntegerField(default=0)),
                ('discipline_name', models.CharField(default='+', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_id', models.IntegerField(default=0)),
                ('style_name', models.CharField(default='+', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField(default=0)),
                ('car_mark', models.CharField(default='+', max_length=50)),
                ('car_name', models.CharField(default='+', max_length=50)),
                ('prod_year', models.IntegerField(default=2000)),
                ('body_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='car.body')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('order_name', models.CharField(default='+', max_length=20)),
                ('order_body_color_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='body_color', to='car.color')),
                ('order_car_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('order_discipline_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='car.discipline')),
                ('order_disk_color_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='disk_color', to='car.color')),
                ('order_interer_color_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='interer_color', to='car.color')),
                ('order_user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_style_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='car.style')),
            ],
        ),
        migrations.CreateModel(
            name='Tunning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tunning_id', models.IntegerField(default=0)),
                ('tunning_name', models.CharField(default='+', max_length=20)),
                ('tunning_body_color_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tunning_body_color', to='car.color')),
                ('tunning_discipline_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='car.discipline')),
                ('tunning_disk_color_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tunning_disk_color', to='car.color')),
                ('tunning_interer_color_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tunning_interer_color', to='car.color')),
                ('tunning_style_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='car.style')),
            ],
        ),
    ]
