# Generated by Django 4.2.16 on 2024-10-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='yom',
            field=models.IntegerField(),
        ),
    ]
