# Generated by Django 5.1.4 on 2024-12-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_car_body_id_remove_car_prod_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status_id', models.IntegerField(default=0)),
                ('order_status_name', models.CharField(default='+', max_length=20)),
            ],
        ),
    ]
