# Generated by Django 5.1.4 on 2024-12-18 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_order_status_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='car.orderstatus'),
        ),
    ]
