# Generated by Django 4.2.16 on 2024-10-17 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tunning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_color', to='tunning.color')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunning.discipline')),
                ('disk_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk_color', to='tunning.color')),
                ('interer_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interer_color', to='tunning.color')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunning.style')),
            ],
        ),
    ]
